import type { Metadata } from "next";
import { Krub, Fira_Code } from "next/font/google";
import "./globals.css";

const krub = Krub({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const firaCode = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${krub.variable} ${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
